# Generated by Django 6.0.1 on 2026-01-24 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_frame', models.ImageField(blank=True, null=True, upload_to='frames/')),
                ('video_snippet', models.FileField(blank=True, null=True, upload_to='snippets/')),
                ('timestamp', models.FloatField(help_text='Second in video where frame/snippet was captured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='incidents.incident')),
            ],
        ),
    ]
