# Generated by Django 6.0.1 on 2026-01-24 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('VIOLENCE', 'Violence'), ('WEAPON', 'Weapon Possession'), ('THEFT', 'Theft')], max_length=20)),
                ('confidence', models.FloatField(help_text='Model confidence score')),
                ('detected_at', models.DateTimeField(help_text='Timestamp in video when incident occurred')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='cameras.videosource')),
            ],
        ),
    ]
