"""
Django settings for gods_eye project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tf2ryo=-i9%3j-v)v)d5krp=tj(!m*#oj^=j35880yiv%k6!j)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'accounts.User'



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'accounts',
    'cameras',
    'detection',
    'incidents',
    'alerts',
    'media_store',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


ROOT_URLCONF = 'gods_eye.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gods_eye.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Legacy single-head YOLO (optional CLI / experiments). Upload pipeline uses GodsEye v2 below.
YOLO_WEIGHTS = BASE_DIR / 'models' / 'best.pt'
DETECTOR = 'MOCK'
YOLO_LABELS = ['VIOLENCE', 'WEAPON', 'THEFT']
YOLO_CONFIDENCE_THRESHOLD = 0.25
YOLO_IMGSZ = 640
YOLO_CLASS_INDEX_TO_INCIDENT = {
    0: 'VIOLENCE',
    1: 'WEAPON',
    2: 'THEFT',
}

# Final GodsEyeEngine checkpoints (copied into models/v2/ — do not point at engine repo in production)
_models_v2 = BASE_DIR / 'models' / 'v2'
GODEYE_V2_WEAPON_WEIGHTS = _models_v2 / 'weapon_detect_best.pt'
GODEYE_V2_VIOLENCE_WEIGHTS = _models_v2 / 'violence_detect_best.pt'
GODEYE_V2_ROBBERY_CLS_WEIGHTS = _models_v2 / 'robbery_cls_best.pt'
GODEYE_V2_WEAPON_IMGSZ = int(os.environ.get('GODEYE_V2_WEAPON_IMGSZ', '640'))
GODEYE_V2_WEAPON_CONF = float(os.environ.get('GODEYE_V2_WEAPON_CONF', '0.25'))
GODEYE_V2_WEAPON_INCIDENT_CONF = float(os.environ.get('GODEYE_V2_WEAPON_INCIDENT_CONF', '0.65'))
GODEYE_V2_WEAPON_EVERY_N_FRAMES = int(os.environ.get('GODEYE_V2_WEAPON_EVERY_N_FRAMES', '1'))
GODEYE_V2_VIOLENCE_IMGSZ = int(os.environ.get('GODEYE_V2_VIOLENCE_IMGSZ', '640'))
GODEYE_V2_VIOLENCE_CONF = float(os.environ.get('GODEYE_V2_VIOLENCE_CONF', '0.25'))
GODEYE_V2_VIOLENCE_INCIDENT_CONF = float(os.environ.get('GODEYE_V2_VIOLENCE_INCIDENT_CONF', '0.35'))
GODEYE_V2_VIOLENCE_EVERY_N_FRAMES = int(os.environ.get('GODEYE_V2_VIOLENCE_EVERY_N_FRAMES', '1'))
# If the violence detector uses class names containing these substrings, only those boxes count;
# empty list = treat all boxes as violence (single-class models).
GODEYE_V2_VIOLENCE_LABEL_MATCH = ['violence', 'fight', 'assault']
GODEYE_V2_CLS_IMGSZ = int(os.environ.get('GODEYE_V2_CLS_IMGSZ', '224'))
GODEYE_V2_CLS_EVERY_N_FRAMES = int(os.environ.get('GODEYE_V2_CLS_EVERY_N_FRAMES', '4'))
# Robbery cls → THEFT: softmax can spike on the wrong frames; temporal smoothing + slightly higher default helps demos.
GODEYE_V2_ROBBERY_CONF = float(os.environ.get('GODEYE_V2_ROBBERY_CONF', '0.72'))
GODEYE_V2_ROBBERY_CLASS_NAME = os.environ.get('GODEYE_V2_ROBBERY_CLASS_NAME', 'robbery')
GODEYE_V2_ROBBERY_TEMPORAL_SMOOTH = os.environ.get('GODEYE_V2_ROBBERY_TEMPORAL_SMOOTH', 'true').lower() in ('1', 'true', 'yes', '')
GODEYE_V2_ROBBERY_SMOOTH_WINDOW = int(os.environ.get('GODEYE_V2_ROBBERY_SMOOTH_WINDOW', '8'))
GODEYE_V2_ROBBERY_SMOOTH_MIN_SAMPLES = int(os.environ.get('GODEYE_V2_ROBBERY_SMOOTH_MIN_SAMPLES', '5'))
GODEYE_V2_ROBBERY_SMOOTH_MIN_PEAK = float(os.environ.get('GODEYE_V2_ROBBERY_SMOOTH_MIN_PEAK', '0.58'))
# Demo switch: disable THEFT/robbery alerts while keeping WEAPON and VIOLENCE active.
GODEYE_V2_ENABLE_THEFT_ALERTS = os.environ.get('GODEYE_V2_ENABLE_THEFT_ALERTS', 'false').lower() in ('1', 'true', 'yes')

# Debounce: minimum seconds between incidents of the same type on one video (live-style ~10–15s)
GODEYE_MIN_SECONDS_BETWEEN_INCIDENTS = float(os.environ.get('GODEYE_MIN_SECONDS_BETWEEN_INCIDENTS', '12'))

# Firebase Cloud Messaging — path to service account JSON (optional; can also use GOOGLE_APPLICATION_CREDENTIALS)
FCM_CREDENTIALS_PATH = os.environ.get("FCM_CREDENTIALS_PATH") or None


# CORS Configuration for Angular Frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",  # Default Angular dev server
    "http://127.0.0.1:4200",
    "http://localhost:8100",  # Ionic dev server (companion receiver app)
    "http://127.0.0.1:8100",
]
# Also allow dynamic localhost dev ports (e.g. Ionic/Capacitor live-reload random ports).
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
]

# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# Allow specific headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Allow specific methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

