# Generated by Django 6.0.1 on 2026-01-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('LIVE', 'Live Camera'), ('UPLOAD', 'Uploaded Video')], max_length=10)),
                ('stream_url', models.URLField(blank=True, help_text='RTSP/HTTP URL for live cameras', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Uploaded video file', null=True, upload_to='videos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
